//! NA_character_ fidelity tests.
//!
//! `RObject::Character` elements are `Option<Arc<str>>`: `None` is R's
//! `NA_character_`, distinguishable end-to-end from the legal string "NA".
//! Fixtures are generated by tests/generate_test_data.R.

// Native-only test file: excluded from wasm32 so `wasm-pack test`
// (which builds every test target) can compile the workspace.
#![cfg(not(target_arch = "wasm32"))]

use flate2::read::GzDecoder;
use rds2rust::{read_rds, write_rds, RObject, VectorData};
use std::fs;
use std::io::Read;
use std::path::Path;
use std::process::Command;
use std::sync::Arc;

fn test_data_exists() -> bool {
    Path::new("tests/data").exists()
}

fn read_test_file(filename: &str) -> Vec<u8> {
    let path = format!("tests/data/{}", filename);
    fs::read(&path).unwrap_or_else(|_| panic!("Failed to read test file: {}", path))
}

/// write_rds gzips by default; decompress to inspect the raw RDS stream.
fn gunzip(bytes: &[u8]) -> Vec<u8> {
    let mut out = Vec::new();
    GzDecoder::new(bytes)
        .read_to_end(&mut out)
        .expect("gunzip failed");
    out
}

fn r_available() -> bool {
    Command::new("R")
        .args(["--version"])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

fn run_r_code(code: &str) -> Result<String, String> {
    let output = Command::new("R")
        .args(["--vanilla", "--slave", "-e", code])
        .output()
        .map_err(|e| e.to_string())?;
    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).to_string())
    } else {
        Err(String::from_utf8_lossy(&output.stderr).to_string())
    }
}

fn unwrap_value(obj: &RObject) -> RObject {
    match obj {
        RObject::WithAttributes { object, .. } => unwrap_value(object),
        RObject::Shared(shared) => {
            let inner = shared.read().expect("shared object lock poisoned");
            unwrap_value(&inner)
        }
        other => other.clone(),
    }
}

fn attr_of<'a>(obj: &'a RObject, name: &str) -> Option<&'a RObject> {
    if let RObject::WithAttributes { attributes, object } = obj {
        if let Some(value) = attributes.get(name) {
            return Some(value);
        }
        return attr_of(object, name);
    }
    None
}

/// A real "NA" string and NA_character_ parse into distinguishable values.
#[test]
fn test_na_distinguishable_from_na_string() {
    if !test_data_exists() {
        eprintln!("Skipping test: test data not generated");
        return;
    }

    // c("NA", NA_character_)
    let data = read_test_file("na_character_basic.rds");
    let obj = read_rds(&data)
        .expect("failed to parse na_character_basic.rds")
        .object;

    match unwrap_value(&obj) {
        RObject::Character(vec) => {
            assert_eq!(vec.len(), 2);
            assert_eq!(vec[0].as_deref(), Some("NA"));
            assert_eq!(vec[1], None);
            assert!(!vec.is_na(0));
            assert!(vec.is_na(1));
            assert_ne!(vec[0], vec[1]);
        }
        other => panic!("expected character vector, got {:?}", other),
    }
}

/// Writing None emits R's exact NA wire form: bare CHARSXP flags 0x00000009
/// followed by int32 -1 (verified against R's own serializer output).
#[test]
fn test_na_writer_wire_form() {
    let obj = RObject::Character(vec![Some(Arc::from("NA")), None].into());
    let bytes = gunzip(&write_rds(&obj).expect("failed to serialize"));

    let na_marker: &[u8] = &[0x00, 0x00, 0x00, 0x09, 0xff, 0xff, 0xff, 0xff];
    assert!(
        bytes.windows(8).any(|w| w == na_marker),
        "output must contain the bare-flags + length -1 NA wire form"
    );
}

/// rds2rust-only roundtrip: parse -> write -> parse preserves NA.
#[test]
fn test_na_roundtrip_rds2rust() {
    let obj = RObject::Character(vec![Some(Arc::from("NA")), None, Some(Arc::from("x"))].into());
    let bytes = write_rds(&obj).expect("failed to serialize");
    let reread = read_rds(&bytes).expect("failed to re-read").object;

    match unwrap_value(&reread) {
        RObject::Character(vec) => {
            assert_eq!(vec[0].as_deref(), Some("NA"));
            assert_eq!(vec[1], None);
            assert_eq!(vec[2].as_deref(), Some("x"));
        }
        other => panic!("expected character vector, got {:?}", other),
    }
}

/// Full fidelity roundtrip verified by R itself: what rds2rust writes,
/// readRDS sees as identical() to the original.
#[test]
fn test_na_roundtrip_through_r() {
    if !r_available() {
        eprintln!("Skipping test: R not available");
        return;
    }

    let obj = RObject::Character(vec![Some(Arc::from("NA")), None].into());
    let bytes = write_rds(&obj).expect("failed to serialize");
    let path = std::env::temp_dir().join("rds2rust_na_character_roundtrip.rds");
    fs::write(&path, &bytes).expect("failed to write file");

    let r_code = format!(
        "x <- readRDS('{}'); \
         stopifnot(identical(x, c('NA', NA_character_))); \
         stopifnot(!is.na(x[1])); \
         stopifnot(is.na(x[2])); \
         cat('PASS')",
        path.display()
    );
    match run_r_code(&r_code) {
        Ok(stdout) => assert!(stdout.contains("PASS"), "R verification failed: {}", stdout),
        Err(err) => panic!("R failed to read roundtripped file: {}", err),
    }
    let _ = fs::remove_file(&path);
}

/// An NA element in a names attribute keeps its position; the names vector
/// surfaces the None slot rather than fabricating a string.
#[test]
fn test_na_in_names_attribute() {
    if !test_data_exists() {
        eprintln!("Skipping test: test data not generated");
        return;
    }

    // list(1L, 2L, 3L) with names c("a", NA, "b")
    let data = read_test_file("na_in_names.rds");
    let obj = read_rds(&data)
        .expect("failed to parse na_in_names.rds")
        .object;

    let names = attr_of(&obj, "names").expect("names attribute should survive");
    match unwrap_value(names) {
        RObject::Character(vec) => {
            assert_eq!(vec.len(), 3);
            assert_eq!(vec[0].as_deref(), Some("a"));
            assert_eq!(vec[1], None);
            assert_eq!(vec[2].as_deref(), Some("b"));
        }
        other => panic!("expected character names, got {:?}", other),
    }

    let items = match unwrap_value(&obj) {
        RObject::List(items) => items,
        other => panic!("expected list, got {:?}", other),
    };
    assert_eq!(items.len(), 3, "positions preserved despite the NA name");
}

/// An NA inside a class vector is skipped (class lookup is order-insensitive
/// and a class name cannot be NA); remaining classes still apply.
#[test]
fn test_na_in_class_vector() {
    if !test_data_exists() {
        eprintln!("Skipping test: test data not generated");
        return;
    }

    // list("payload") with class attr c("foo", NA, "bar")
    let data = read_test_file("na_in_class.rds");
    let obj = read_rds(&data)
        .expect("failed to parse na_in_class.rds")
        .object;

    match unwrap_value(&obj) {
        RObject::S3Object(s3) => {
            let classes: Vec<&str> = s3.class.iter().map(|c| c.as_ref()).collect();
            assert_eq!(classes, ["foo", "bar"], "NA class entry skipped");
        }
        other => panic!("expected S3 object, got {}", other.variant_name()),
    }
}

/// A factor with an NA level keeps the level slot positionally: values
/// indexing later levels must still resolve correctly.
#[test]
fn test_na_factor_level_preserves_slots() {
    if !test_data_exists() {
        eprintln!("Skipping test: test data not generated");
        return;
    }

    // factor(c("a", NA, "b"), exclude = NULL): levels ["a", "b", NA],
    // values [1, 3, 2]
    let data = read_test_file("na_factor_level.rds");
    let obj = read_rds(&data)
        .expect("failed to parse na_factor_level.rds")
        .object;

    match unwrap_value(&obj) {
        RObject::Factor(f) => {
            assert_eq!(f.values, [1, 3, 2]);
            assert_eq!(f.levels.len(), 3);
            assert_eq!(f.levels[0].as_deref(), Some("a"));
            assert_eq!(f.levels[1].as_deref(), Some("b"));
            assert_eq!(f.levels[2], None, "NA level keeps its slot");
        }
        other => panic!("expected factor, got {}", other.variant_name()),
    }
}

/// A data-frame string column distinguishes "NA" from NA.
#[test]
fn test_na_in_dataframe_column() {
    if !test_data_exists() {
        eprintln!("Skipping test: test data not generated");
        return;
    }

    // data.frame(s = c("NA", NA, "x"))
    let data = read_test_file("na_df_column.rds");
    let obj = read_rds(&data)
        .expect("failed to parse na_df_column.rds")
        .object;

    let df = match unwrap_value(&obj) {
        RObject::DataFrame(df) => df,
        other => panic!("expected data frame, got {}", other.variant_name()),
    };
    let col = df.columns.get("s").expect("column s");
    match unwrap_value(col) {
        RObject::Character(vec) => {
            assert_eq!(vec[0].as_deref(), Some("NA"));
            assert_eq!(vec[1], None);
            assert_eq!(vec[2].as_deref(), Some("x"));
        }
        other => panic!("expected character column, got {:?}", other),
    }
}

/// The dedup cache never conflates c("NA") with c(NA_character_).
#[test]
fn test_na_dedup_distinctness() {
    if !test_data_exists() {
        eprintln!("Skipping test: test data not generated");
        return;
    }

    // list(x = "NA", y = NA_character_)
    let data = read_test_file("na_dedup.rds");
    let obj = read_rds(&data)
        .expect("failed to parse na_dedup.rds")
        .object;

    let items = match unwrap_value(&obj) {
        RObject::List(items) => items,
        other => panic!("expected list, got {:?}", other),
    };
    let x = match unwrap_value(&items[0]) {
        RObject::Character(v) => v,
        other => panic!("x should be character, got {:?}", other),
    };
    let y = match unwrap_value(&items[1]) {
        RObject::Character(v) => v,
        other => panic!("y should be character, got {:?}", other),
    };
    assert_eq!(x[0].as_deref(), Some("NA"));
    assert_eq!(y[0], None);
    assert_ne!(x.as_vec(), y.as_vec());
}

/// Helper affordances: construction, access, iteration, and the explicit
/// render-NA escape hatch.
#[test]
fn test_character_vector_helpers() {
    let v: VectorData<Option<Arc<str>>> = VectorData::from_strs(["a", "b"]);
    assert_eq!(v.len(), 2);
    assert_eq!(v.get_str(0), Some("a"));
    assert!(!v.is_na(0));

    let with_na: VectorData<Option<Arc<str>>> =
        vec![Some(Arc::from("a")), None, Some(Arc::from("NA"))].into();
    assert_eq!(with_na.get_str(1), None);
    assert!(with_na.is_na(1));
    assert!(!with_na.is_na(2), "the string \"NA\" is not missing");

    let strs: Vec<Option<&str>> = with_na.iter_strs().collect();
    assert_eq!(strs, [Some("a"), None, Some("NA")]);

    // Escape hatch reproduces the old rendering in one visible call.
    assert_eq!(with_na.to_strings_with_na("NA"), ["a", "NA", "NA"]);
    // R's own display convention.
    assert_eq!(with_na.to_strings_with_na("<NA>"), ["a", "<NA>", "NA"]);
}

/// NA_character_ in a symbol-name position is a parse error, not a symbol
/// named "NA" (R has no NA symbols). Hand-built version-2 XDR stream:
/// SYMSXP whose name CHARSXP carries the NA marker (length -1).
#[test]
fn test_na_symbol_name_rejected() {
    let mut data: Vec<u8> = Vec::new();
    data.extend_from_slice(b"X\n"); // XDR format marker
    data.extend_from_slice(&2i32.to_be_bytes()); // serialization version 2
    data.extend_from_slice(&0x040303i32.to_be_bytes()); // writer R version
    data.extend_from_slice(&0x020300i32.to_be_bytes()); // min reader R version
    data.extend_from_slice(&1i32.to_be_bytes()); // SYMSXP flags
    data.extend_from_slice(&9i32.to_be_bytes()); // CHARSXP flags (bare)
    data.extend_from_slice(&(-1i32).to_be_bytes()); // NA marker

    let err = format!(
        "{:?}",
        read_rds(&data).expect_err("NA symbol name must be rejected")
    );
    assert!(
        err.contains("symbol name"),
        "unexpected error for NA symbol name: {}",
        err
    );
}

/// In-memory input source for lazy range reads.
struct BytesInput {
    data: Vec<u8>,
}

impl rds2rust::RdsInput for BytesInput {
    fn read_at(&self, offset: u64, len: usize) -> rds2rust::Result<Vec<u8>> {
        let start = offset as usize;
        let end = (start + len).min(self.data.len());
        Ok(self.data[start..end.max(start)].to_vec())
    }

    fn len(&self) -> Option<u64> {
        Some(self.data.len() as u64)
    }
}

/// Native lazy-range reads surface NA as None, not a fabricated "NA".
#[test]
fn test_na_lazy_character_range() {
    // Build a vector large enough to stay lazy in lazy mode, with an NA in a
    // known position, write it, and range-read through the lazy machinery.
    let mut values: Vec<Option<Arc<str>>> = (0..60)
        .map(|i| Some(Arc::from(format!("v{}", i).as_str())))
        .collect();
    values[7] = None;
    let obj = RObject::Character(values.into());
    // Lazy spans reference offsets in the uncompressed stream.
    let bytes = gunzip(&write_rds(&obj).expect("failed to serialize"));

    let lazy = rds2rust::read_rds_lazy(&bytes)
        .expect("failed lazy parse")
        .object;
    let span = match unwrap_value(&lazy) {
        RObject::Character(VectorData::Lazy(span)) => span,
        other => panic!("expected lazy character vector, got {:?}", other),
    };

    let input = BytesInput { data: bytes };
    let chunk = rds2rust::read_lazy_character_range(&input, span, 5, 5).expect("range read failed");
    assert_eq!(chunk.len(), 5);
    assert_eq!(chunk[0].as_deref(), Some("v5"));
    assert_eq!(chunk[2], None, "NA at absolute index 7");
    assert_eq!(chunk[3].as_deref(), Some("v8"));
}
