//! Tests for PACKAGESXP entries (serialized package environments).
//!
//! R writes a package environment as PACKAGESXP followed by an OutStringVec
//! payload holding the environment's name (e.g. "package:stats"), and the
//! entry occupies one reference slot (AddReadRef). The payload must be
//! consumed during parsing, otherwise the cursor desynchronizes and every
//! object after the entry is corrupted.
//!
//! Fixtures are generated by tests/generate_test_data.R.

use rds2rust::{
    read_rds, traverse_rds_streaming, ObjectPath, ParseConfig, RObject, RdsVisitor, VisitAction,
};
use std::path::Path;
use std::sync::Arc;

fn test_data_exists() -> bool {
    Path::new("tests/data").exists()
}

fn read_test_file(filename: &str) -> Vec<u8> {
    let path = format!("tests/data/{}", filename);
    std::fs::read(&path).unwrap_or_else(|_| panic!("Failed to read test file: {}", path))
}

/// Unwrap attribute wrappers and shared references down to the plain object.
fn unwrap_value(obj: &RObject) -> RObject {
    match obj {
        RObject::WithAttributes { object, .. } => unwrap_value(object),
        RObject::Shared(shared) => {
            let inner = shared.read().expect("shared object lock poisoned");
            unwrap_value(&inner)
        }
        other => other.clone(),
    }
}

fn attr_of<'a>(obj: &'a RObject, name: &str) -> Option<&'a RObject> {
    if let RObject::WithAttributes { attributes, object } = obj {
        if let Some(value) = attributes.get(name) {
            return Some(value);
        }
        return attr_of(object, name);
    }
    None
}

fn character_values(obj: &RObject) -> Vec<String> {
    match unwrap_value(obj) {
        RObject::Character(values) => values.to_strings_with_na("<NA>"),
        other => panic!("expected character vector, got {:?}", other),
    }
}

fn namespace_values(obj: &RObject) -> Vec<String> {
    match unwrap_value(obj) {
        RObject::Namespace(names) => names.iter().map(|s| s.to_string()).collect(),
        other => panic!("expected namespace, got {}", other.variant_name()),
    }
}

fn shared_arc(obj: &RObject) -> Option<Arc<std::sync::RwLock<RObject>>> {
    match obj {
        RObject::Shared(arc) => Some(Arc::clone(arc)),
        _ => None,
    }
}

#[test]
fn test_packagesxp_bare() {
    if !test_data_exists() {
        eprintln!("Skipping test: test data not generated");
        return;
    }

    // serialize(as.environment("package:stats"))
    let data = read_test_file("packagesxp_bare.rds");
    let obj = read_rds(&data)
        .expect("failed to parse packagesxp_bare.rds")
        .object;
    assert_eq!(namespace_values(&obj), ["package:stats"]);
}

#[test]
fn test_packagesxp_stream_alignment() {
    if !test_data_exists() {
        eprintln!("Skipping test: test data not generated");
        return;
    }

    // list(p = pkg_env, after = "still-aligned")
    let data = read_test_file("packagesxp.rds");
    let obj = read_rds(&data)
        .expect("failed to parse packagesxp.rds")
        .object;

    let names = attr_of(&obj, "names").expect("list names should survive");
    assert_eq!(character_values(names), ["p", "after"]);

    let items = match unwrap_value(&obj) {
        RObject::List(items) => items,
        other => panic!("expected list, got {:?}", other),
    };
    assert_eq!(items.len(), 2);

    assert_eq!(namespace_values(&items[0]), ["package:stats"]);

    // The critical assertion: the object after the package entry parses
    // correctly, proving the PACKAGESXP payload was consumed.
    assert_eq!(character_values(&items[1]), ["still-aligned"]);
}

#[test]
fn test_packagesxp_ref_slots() {
    if !test_data_exists() {
        eprintln!("Skipping test: test data not generated");
        return;
    }

    // list(p = pkg_env, p2 = pkg_env, s = as.name("pkgsym"),
    //      s2 = as.name("pkgsym"), tail = "ref-ok")
    // p2 and s2 are REFSXP back references; they only resolve correctly if
    // PACKAGESXP occupies exactly one reference slot (matching AddReadRef)
    // and that slot holds the package object rather than a placeholder.
    let data = read_test_file("packagesxp_refs.rds");
    let obj = read_rds(&data)
        .expect("failed to parse packagesxp_refs.rds")
        .object;

    let items = match unwrap_value(&obj) {
        RObject::List(items) => items,
        other => panic!("expected list, got {:?}", other),
    };
    assert_eq!(items.len(), 5);

    assert_eq!(namespace_values(&items[0]), ["package:stats"]);
    assert_eq!(namespace_values(&items[1]), ["package:stats"]);

    // Both occurrences must resolve to the same shared object.
    let p = shared_arc(&items[0]).expect("p should be Shared");
    let p2 = shared_arc(&items[1]).expect("p2 should be Shared");
    assert!(
        Arc::ptr_eq(&p, &p2),
        "p and p2 should point to the same shared package environment"
    );

    match unwrap_value(&items[2]) {
        RObject::Symbol(name) => assert_eq!(name.as_ref(), "pkgsym"),
        other => panic!("s should be a symbol, got {}", other.variant_name()),
    }
    match unwrap_value(&items[3]) {
        RObject::Symbol(name) => assert_eq!(name.as_ref(), "pkgsym"),
        other => panic!("s2 should be a symbol, got {}", other.variant_name()),
    }
    assert_eq!(character_values(&items[4]), ["ref-ok"]);
}

#[test]
fn test_packagesxp_in_attributes() {
    if !test_data_exists() {
        eprintln!("Skipping test: test data not generated");
        return;
    }

    // structure(list("payload"), pkgenv = pkg_env, tail_attr = "tail")
    let data = read_test_file("packagesxp_attr.rds");
    let obj = read_rds(&data)
        .expect("failed to parse packagesxp_attr.rds")
        .object;

    let pkgenv = attr_of(&obj, "pkgenv").expect("pkgenv attribute should survive");
    assert_eq!(namespace_values(pkgenv), ["package:stats"]);

    let tail_attr = attr_of(&obj, "tail_attr").expect("tail_attr attribute should survive");
    assert_eq!(character_values(tail_attr), ["tail"]);

    let items = match unwrap_value(&obj) {
        RObject::List(items) => items,
        other => panic!("expected list, got {:?}", other),
    };
    assert_eq!(items.len(), 1);
    assert_eq!(character_values(&items[0]), ["payload"]);
}

#[derive(Default)]
struct CollectingVisitor {
    vector_metadata: Vec<(rds2rust::VectorKind, usize)>,
    attr_keys: Vec<String>,
}

impl RdsVisitor for CollectingVisitor {
    type Error = std::convert::Infallible;

    fn on_object_start(
        &mut self,
        _path: &ObjectPath,
        _obj_type: &str,
    ) -> Result<VisitAction, Self::Error> {
        Ok(VisitAction::Continue)
    }

    fn on_vector_metadata(
        &mut self,
        _path: &ObjectPath,
        vec_type: rds2rust::VectorKind,
        len: usize,
    ) -> Result<(), Self::Error> {
        self.vector_metadata.push((vec_type, len));
        Ok(())
    }

    fn on_attributes(
        &mut self,
        _path: &ObjectPath,
        attrs: &rds2rust::Attributes,
    ) -> Result<(), Self::Error> {
        self.attr_keys
            .extend(attrs.iter().map(|(key, _)| key.to_string()));
        Ok(())
    }
}

#[cfg(not(target_arch = "wasm32"))]
#[test]
fn test_packagesxp_streaming_alignment() {
    if !test_data_exists() {
        eprintln!("Skipping test: test data not generated");
        return;
    }

    let source = rds2rust::MmapRdsSource::from_path(Path::new("tests/data/packagesxp.rds"))
        .expect("failed to open packagesxp.rds");
    let mut visitor = CollectingVisitor::default();
    traverse_rds_streaming(&source, ParseConfig::default(), &mut visitor)
        .expect("streaming traversal must consume PACKAGESXP payloads");

    // With the PACKAGESXP payload consumed, the traversal sees the trailing
    // "still-aligned" element (length 1) and the list names (length 2).
    // A desynchronized stream misreads both and drops the names attribute.
    assert_eq!(
        visitor.vector_metadata,
        [
            (rds2rust::VectorKind::Character, 1),
            (rds2rust::VectorKind::Character, 2),
        ]
    );
    assert_eq!(visitor.attr_keys, ["names"]);
}

#[test]
fn test_namespacesxp_alignment() {
    if !test_data_exists() {
        eprintln!("Skipping test: test data not generated");
        return;
    }

    // list(ns = getNamespace("stats"), after = "ns-aligned")
    let data = read_test_file("namespacesxp.rds");
    let obj = read_rds(&data)
        .expect("failed to parse namespacesxp.rds")
        .object;

    let items = match unwrap_value(&obj) {
        RObject::List(items) => items,
        other => panic!("expected list, got {:?}", other),
    };
    assert_eq!(items.len(), 2);

    // R writes the namespace spec as c(name, version).
    assert_eq!(namespace_values(&items[0])[0], "stats");
    assert_eq!(character_values(&items[1]), ["ns-aligned"]);
}

#[test]
fn test_basenamespace_alignment() {
    if !test_data_exists() {
        eprintln!("Skipping test: test data not generated");
        return;
    }

    // list(b = getNamespace("base"), after = "base-ok")
    // BASENAMESPACE_SXP (250) has NO payload on the wire; reading a phantom
    // OutStringVec here used to swallow the next element.
    let data = read_test_file("basenamespace.rds");
    let obj = read_rds(&data)
        .expect("failed to parse basenamespace.rds")
        .object;

    let names = attr_of(&obj, "names").expect("list names should survive");
    assert_eq!(character_values(names), ["b", "after"]);

    let items = match unwrap_value(&obj) {
        RObject::List(items) => items,
        other => panic!("expected list, got {:?}", other),
    };
    assert_eq!(items.len(), 2);

    assert_eq!(namespace_values(&items[0]), ["base"]);
    assert_eq!(character_values(&items[1]), ["base-ok"]);
}

/// Build a hand-crafted version-2 XDR stream: header followed by `body`.
fn v2_stream(body: &[i32]) -> Vec<u8> {
    let mut data: Vec<u8> = Vec::new();
    data.extend_from_slice(b"X\n"); // XDR format marker
    data.extend_from_slice(&2i32.to_be_bytes()); // serialization version 2
    data.extend_from_slice(&0x040303i32.to_be_bytes()); // writer R version
    data.extend_from_slice(&0x020300i32.to_be_bytes()); // min reader R version
    for word in body {
        data.extend_from_slice(&word.to_be_bytes());
    }
    data
}

/// A PACKAGESXP payload declaring a negative (non-long-vector-marker) string
/// count must be rejected with an error, not a panic or a silent desync.
#[test]
fn test_packagesxp_negative_count_rejected() {
    // PACKAGESXP flags, names placeholder, invalid count
    let data = v2_stream(&[248, 0, -2]);
    let result = read_rds(&data);
    assert!(
        result.is_err(),
        "negative string vector count must be rejected, got {:?}",
        result.map(|r| r.object.variant_name().to_string())
    );
}

/// R's InStringVec errors on a non-zero names placeholder; so do we. The
/// stream is otherwise complete and valid, so a parser that ignores the
/// placeholder would succeed - the assertion checks for the specific
/// validation error, not just any failure.
#[test]
fn test_stringvec_nonzero_names_placeholder_rejected() {
    // PACKAGESXP flags, names placeholder = 1, count = 1,
    // CHARSXP flags (UTF-8), length 1
    let mut data = v2_stream(&[248, 1, 1, 0x00040009, 1]);
    data.push(b'x');
    let err = format!(
        "{:?}",
        read_rds(&data).expect_err("non-zero names placeholder must be rejected")
    );
    assert!(err.contains("names marker"), "unexpected error: {}", err);
}

/// Each string-vec item must be an inline CHARSXP; any other type in the item
/// flags word means the stream is corrupt and must not be misread as string
/// bytes. The stream is shaped so a parser without the type check would
/// happily misread the payload as a one-character string.
#[test]
fn test_stringvec_wrong_item_type_rejected() {
    // PACKAGESXP flags, placeholder 0, count 1, item flags = INTSXP (13),
    // "length" 1
    let mut data = v2_stream(&[248, 0, 1, 13, 1]);
    data.push(b'x');
    let err = format!(
        "{:?}",
        read_rds(&data).expect_err("non-CHARSXP string vector item must be rejected")
    );
    assert!(
        err.contains("expected CHARSXP"),
        "unexpected error: {}",
        err
    );
}

/// GENERICREFSXP (245) / CLASSREFSXP (246): R's own reader errors on these
/// unconditionally, so no readable stream contains them. Previously the
/// parser resolved `flags >> 8` against the main reference table, returning
/// an arbitrary wrong object.
#[test]
fn test_generic_class_refs_rejected() {
    for ref_type in [245, 246] {
        let data = v2_stream(&[ref_type]);
        let err = format!(
            "{:?}",
            read_rds(&data).expect_err("generic/class reference must be rejected")
        );
        assert!(
            err.contains("cannot be read"),
            "unexpected error for type {}: {}",
            ref_type,
            err
        );
    }
}

/// BCREPREF (243) / BCREPDEF (244) only occur inside bytecode payloads (where
/// parse_bc_lang decodes them with a dedicated reps table). At top level they
/// mean the stream is corrupt; previously the parser resolved `flags >> 8`
/// against the main reference table, returning an arbitrary wrong object.
#[test]
fn test_bcrep_outside_bytecode_rejected() {
    for bcrep_type in [243, 244] {
        let data = v2_stream(&[bcrep_type]);
        let result = read_rds(&data);
        assert!(
            result.is_err(),
            "type {} outside bytecode must be rejected, got {:?}",
            bcrep_type,
            result.map(|r| r.object.variant_name().to_string())
        );
    }
}
