//! Regression tests for REFSXP index alignment.
//!
//! R's serializer assigns reference indices only to symbols, environments,
//! external pointers, weak references and persisted objects. If the reader
//! tracks additional types (vectors, lists, closures, ...), every REFSXP
//! index is shifted and back references resolve to the wrong object (in the
//! worst case to the enclosing structure itself, creating a spurious cycle).
//!
//! Fixtures are generated by tests/generate_test_data.R.

use rds2rust::{
    read_rds, traverse_rds_streaming, write_rds, ObjectPath, RObject, RdsVisitor, VisitAction,
};
use std::fs;
use std::path::Path;
use std::process::Command;
use std::sync::Arc;

fn test_data_exists() -> bool {
    Path::new("tests/data").exists()
}

fn r_available() -> bool {
    Command::new("R")
        .args(["--version"])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

fn run_r_code(code: &str) -> Result<String, String> {
    let output = Command::new("R")
        .args(["--vanilla", "--slave", "-e", code])
        .output()
        .map_err(|e| e.to_string())?;

    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).to_string())
    } else {
        Err(String::from_utf8_lossy(&output.stderr).to_string())
    }
}

fn read_test_file(filename: &str) -> Vec<u8> {
    let path = format!("tests/data/{}", filename);
    fs::read(&path).unwrap_or_else(|_| panic!("Failed to read test file: {}", path))
}

/// Unwrap a top-level WithAttributes list into its elements.
/// Tolerates Shared wrappers so the assertions below can report the actual
/// misresolved element instead of failing on representation differences.
fn unwrap_named_list(obj: RObject) -> Vec<RObject> {
    match obj.into_concrete() {
        RObject::WithAttributes { object, .. } => match object.into_concrete() {
            RObject::List(items) => items,
            other => panic!("Expected List, got {}", other.variant_name()),
        },
        RObject::List(items) => items,
        other => panic!("Expected named list, got {}", other.variant_name()),
    }
}

/// Assert that an element resolves to the expected symbol without descending
/// into potentially cyclic structures (a misresolved back reference can point
/// at the enclosing list itself, so `{:?}`-style formatting must be avoided).
fn assert_symbol(items: &[RObject], index: usize, expected: &str) {
    match items[index].as_concrete() {
        RObject::Symbol(name) => assert_eq!(
            name.as_ref(),
            expected,
            "items[{}] resolved to symbol '{}', expected '{}'",
            index,
            name,
            expected
        ),
        other => panic!(
            "items[{}] resolved to {} instead of Symbol({})",
            index,
            other.variant_name(),
            expected
        ),
    }
}

fn assert_string(items: &[RObject], index: usize, expected: &str) {
    match items[index].as_concrete() {
        RObject::Character(values) => {
            assert_eq!(values.len(), 1);
            assert_eq!(values[0].as_ref(), expected);
        }
        other => panic!(
            "items[{}] resolved to {} instead of Character",
            index,
            other.variant_name()
        ),
    }
}

/// Extract the Shared Arc from an element, if any.
fn shared_arc(obj: &RObject) -> Option<Arc<std::sync::RwLock<RObject>>> {
    match obj {
        RObject::Shared(arc) => Some(Arc::clone(arc)),
        _ => None,
    }
}

#[test]
fn test_shared_symbol_backreference() {
    if !test_data_exists() {
        eprintln!("Warning: tests/data directory not found, skipping test");
        return;
    }

    // list(a = as.name("foo"), b = as.name("foo"), tail = "ok")
    let data = read_test_file("refsxp_shared_symbol.rds");
    let obj = read_rds(&data).expect("Failed to parse").object;
    let items = unwrap_named_list(obj);
    assert_eq!(items.len(), 3);

    assert_symbol(&items, 0, "foo");
    // Before the reference-table fix, the REFSXP for `b` resolved to the
    // top-level list itself (a spurious cycle) instead of the symbol.
    assert_symbol(&items, 1, "foo");
    assert_string(&items, 2, "ok");

    // Both occurrences must resolve to the same shared object.
    if let (Some(a), Some(b)) = (shared_arc(&items[0]), shared_arc(&items[1])) {
        assert!(
            Arc::ptr_eq(&a, &b),
            "a and b should point to the same shared symbol"
        );
    }
}

#[test]
fn test_shared_env_interleaved_with_symbols() {
    if !test_data_exists() {
        eprintln!("Warning: tests/data directory not found, skipping test");
        return;
    }

    // list(s1 = sym_before, e1 = env, s2 = sym_after,
    //      s1b = sym_before, e2 = env, s2b = sym_after, tail = "ref-aligned")
    // Reference table written by R: [env, sym_before(?), ...] depending on
    // frame layout; what matters is that all back references resolve to the
    // objects of the correct type and name.
    let data = read_test_file("refsxp_shared_env.rds");
    let obj = read_rds(&data).expect("Failed to parse").object;
    let items = unwrap_named_list(obj);
    assert_eq!(items.len(), 7);

    assert_symbol(&items, 0, "sym_before");
    assert!(
        matches!(items[1].as_concrete(), RObject::Environment { .. }),
        "e1 should be an environment, got {}",
        items[1].as_concrete().variant_name()
    );
    assert_symbol(&items, 2, "sym_after");
    assert_symbol(&items, 3, "sym_before");
    assert!(
        matches!(items[4].as_concrete(), RObject::Environment { .. }),
        "e2 should be an environment, got {}",
        items[4].as_concrete().variant_name()
    );
    // The back reference registered after the environment: only resolves
    // correctly when the reader tracks exactly the same types as R's writer.
    assert_symbol(&items, 5, "sym_after");
    assert_string(&items, 6, "ref-aligned");

    // The two environment occurrences must be the same shared object.
    let e1 = shared_arc(&items[1]).expect("e1 should be Shared");
    let e2 = shared_arc(&items[4]).expect("e2 should be Shared");
    assert!(
        Arc::ptr_eq(&e1, &e2),
        "e1 and e2 should point to the same shared environment"
    );
}

#[test]
fn test_symbol_backreference_after_vectors() {
    if !test_data_exists() {
        eprintln!("Warning: tests/data directory not found, skipping test");
        return;
    }

    // list(x = c(10L, 20L, 30L), nm = as.name("bar"), y = c("a", "b"),
    //      nested = list(z = c(1.5, 2.5)), nm2 = as.name("bar"),
    //      tail = "after-vectors")
    let data = read_test_file("refsxp_symbol_after_vectors.rds");
    let obj = read_rds(&data).expect("Failed to parse").object;
    let items = unwrap_named_list(obj);
    assert_eq!(items.len(), 6);

    match items[0].as_concrete() {
        RObject::Integer(values) => assert_eq!(values.as_vec(), &vec![10, 20, 30]),
        other => panic!("x should be Integer, got {}", other.variant_name()),
    }
    // Vectors are never reference-tracked by R, so they must not be wrapped
    // in Shared (which would indicate they consumed a reference slot).
    assert!(
        shared_arc(&items[0]).is_none(),
        "atomic vectors must not consume reference slots"
    );

    assert_symbol(&items, 1, "bar");
    // If vectors or lists consumed reference slots, this back reference
    // would resolve past the intended entry.
    assert_symbol(&items, 4, "bar");
    assert_string(&items, 5, "after-vectors");
}

/// Visitor that counts objects and shared references while checking that the
/// traversal terminates (a misaligned reference table can produce spurious
/// cycles).
#[derive(Default)]
struct CountingVisitor {
    objects: usize,
    shared_refs: usize,
    symbols: usize,
    environments: usize,
}

impl RdsVisitor for CountingVisitor {
    type Error = std::convert::Infallible;

    fn on_object_start(
        &mut self,
        _path: &ObjectPath,
        obj_type: &str,
    ) -> Result<VisitAction, Self::Error> {
        self.objects += 1;
        match obj_type {
            "Symbol" => self.symbols += 1,
            "Environment" => self.environments += 1,
            _ => {}
        }
        Ok(VisitAction::Continue)
    }

    fn on_shared_reference(
        &mut self,
        _path: &ObjectPath,
        _target: Option<&ObjectPath>,
    ) -> Result<(), Self::Error> {
        self.shared_refs += 1;
        Ok(())
    }
}

#[test]
fn test_streaming_traversal_of_shared_env() {
    if !test_data_exists() {
        eprintln!("Warning: tests/data directory not found, skipping test");
        return;
    }

    let source = rds2rust::MmapRdsSource::from_path(Path::new("tests/data/refsxp_shared_env.rds"))
        .expect("Failed to open fixture");
    let mut visitor = CountingVisitor::default();
    traverse_rds_streaming(&source, rds2rust::ParseConfig::default(), &mut visitor)
        .expect("Streaming traversal failed");

    // s1b, e2, s2b are back references; the frame of the environment may add
    // more. What matters is that the traversal sees the shared entries and
    // the environment exactly once each.
    assert!(
        visitor.shared_refs >= 3,
        "expected at least 3 shared references, got {}",
        visitor.shared_refs
    );
    assert_eq!(
        visitor.environments, 1,
        "the environment should be visited once (back references are REFSXP)"
    );
    assert!(visitor.symbols >= 2, "symbols: {}", visitor.symbols);
}

#[test]
fn test_shared_env_roundtrip() {
    if !test_data_exists() {
        eprintln!("Warning: tests/data directory not found, skipping test");
        return;
    }

    let data = read_test_file("refsxp_shared_env.rds");
    let obj = read_rds(&data).expect("Failed to parse").object;
    let output = write_rds(&obj).expect("Failed to serialize");

    // Re-read with rds2rust: the same alignment invariants must hold.
    let reread = read_rds(&output).expect("Failed to re-read roundtripped data");
    let items = unwrap_named_list(reread.object);
    assert_eq!(items.len(), 7);
    assert_symbol(&items, 0, "sym_before");
    assert_symbol(&items, 2, "sym_after");
    assert_symbol(&items, 3, "sym_before");
    assert_symbol(&items, 5, "sym_after");
    assert_string(&items, 6, "ref-aligned");

    // Verify with R itself: symbols and environments must survive the
    // roundtrip, and both environment occurrences must stay identical.
    if !r_available() {
        eprintln!("Warning: R not available, skipping R verification");
        return;
    }
    let output_path = "/tmp/rds2rust_refsxp_alignment_roundtrip.rds";
    fs::write(output_path, &output).expect("Failed to write roundtripped file");
    let r_code = format!(
        "x <- readRDS('{}'); \
         stopifnot(identical(x$s1, as.name('sym_before'))); \
         stopifnot(identical(x$s2, as.name('sym_after'))); \
         stopifnot(identical(x$s1b, as.name('sym_before'))); \
         stopifnot(identical(x$s2b, as.name('sym_after'))); \
         stopifnot(is.environment(x$e1)); \
         stopifnot(identical(x$e1, x$e2)); \
         stopifnot(identical(x$tail, 'ref-aligned')); \
         cat('PASS')",
        output_path
    );
    match run_r_code(&r_code) {
        Ok(stdout) => assert!(
            stdout.contains("PASS"),
            "R verification did not pass: {}",
            stdout
        ),
        Err(err) => panic!("R failed to read roundtripped file: {}", err),
    }
    let _ = fs::remove_file(output_path);
}
