//! Regression tests for REFSXP index alignment.
//!
//! R's serializer assigns reference indices only to symbols, environments,
//! external pointers, weak references and persisted objects. If the reader
//! tracks additional types (vectors, lists, closures, ...), every REFSXP
//! index is shifted and back references resolve to the wrong object (in the
//! worst case to the enclosing structure itself, creating a spurious cycle).
//!
//! Fixtures are generated by tests/generate_test_data.R.

use rds2rust::{
    read_rds, traverse_rds_streaming, write_rds, ObjectPath, PairlistElement, RObject, RdsVisitor,
    VisitAction,
};
use std::fs;
use std::path::Path;
use std::process::Command;
use std::sync::Arc;

fn test_data_exists() -> bool {
    Path::new("tests/data").exists()
}

fn r_available() -> bool {
    Command::new("R")
        .args(["--version"])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

fn run_r_code(code: &str) -> Result<String, String> {
    let output = Command::new("R")
        .args(["--vanilla", "--slave", "-e", code])
        .output()
        .map_err(|e| e.to_string())?;

    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).to_string())
    } else {
        Err(String::from_utf8_lossy(&output.stderr).to_string())
    }
}

fn read_test_file(filename: &str) -> Vec<u8> {
    let path = format!("tests/data/{}", filename);
    fs::read(&path).unwrap_or_else(|_| panic!("Failed to read test file: {}", path))
}

/// Unwrap a top-level WithAttributes list into its elements.
/// Tolerates Shared wrappers so the assertions below can report the actual
/// misresolved element instead of failing on representation differences.
fn unwrap_named_list(obj: RObject) -> Vec<RObject> {
    match obj.into_concrete() {
        RObject::WithAttributes { object, .. } => match object.into_concrete() {
            RObject::List(items) => items,
            other => panic!("Expected List, got {}", other.variant_name()),
        },
        RObject::List(items) => items,
        other => panic!("Expected named list, got {}", other.variant_name()),
    }
}

/// Assert that an element resolves to the expected symbol without descending
/// into potentially cyclic structures (a misresolved back reference can point
/// at the enclosing list itself, so `{:?}`-style formatting must be avoided).
fn assert_symbol(items: &[RObject], index: usize, expected: &str) {
    match items[index].as_concrete() {
        RObject::Symbol(name) => assert_eq!(
            name.as_ref(),
            expected,
            "items[{}] resolved to symbol '{}', expected '{}'",
            index,
            name,
            expected
        ),
        other => panic!(
            "items[{}] resolved to {} instead of Symbol({})",
            index,
            other.variant_name(),
            expected
        ),
    }
}

fn assert_string(items: &[RObject], index: usize, expected: &str) {
    match items[index].as_concrete() {
        RObject::Character(values) => {
            assert_eq!(values.len(), 1);
            assert_eq!(values[0].as_deref(), Some(expected.as_ref()));
        }
        other => panic!(
            "items[{}] resolved to {} instead of Character",
            index,
            other.variant_name()
        ),
    }
}

/// Extract the Shared Arc from an element, if any.
fn shared_arc(obj: &RObject) -> Option<Arc<std::sync::RwLock<RObject>>> {
    match obj {
        RObject::Shared(arc) => Some(Arc::clone(arc)),
        _ => None,
    }
}

#[test]
fn test_shared_symbol_backreference() {
    if !test_data_exists() {
        eprintln!("Warning: tests/data directory not found, skipping test");
        return;
    }

    // list(a = as.name("foo"), b = as.name("foo"), tail = "ok")
    let data = read_test_file("refsxp_shared_symbol.rds");
    let obj = read_rds(&data).expect("Failed to parse").object;
    let items = unwrap_named_list(obj);
    assert_eq!(items.len(), 3);

    assert_symbol(&items, 0, "foo");
    // Before the reference-table fix, the REFSXP for `b` resolved to the
    // top-level list itself (a spurious cycle) instead of the symbol.
    assert_symbol(&items, 1, "foo");
    assert_string(&items, 2, "ok");

    // Both occurrences must resolve to the same shared object.
    if let (Some(a), Some(b)) = (shared_arc(&items[0]), shared_arc(&items[1])) {
        assert!(
            Arc::ptr_eq(&a, &b),
            "a and b should point to the same shared symbol"
        );
    }
}

#[test]
fn test_shared_env_interleaved_with_symbols() {
    if !test_data_exists() {
        eprintln!("Warning: tests/data directory not found, skipping test");
        return;
    }

    // list(s1 = sym_before, e1 = env, s2 = sym_after,
    //      s1b = sym_before, e2 = env, s2b = sym_after, tail = "ref-aligned")
    // Reference table written by R: [env, sym_before(?), ...] depending on
    // frame layout; what matters is that all back references resolve to the
    // objects of the correct type and name.
    let data = read_test_file("refsxp_shared_env.rds");
    let obj = read_rds(&data).expect("Failed to parse").object;
    let items = unwrap_named_list(obj);
    assert_eq!(items.len(), 7);

    assert_symbol(&items, 0, "sym_before");
    assert!(
        matches!(items[1].as_concrete(), RObject::Environment { .. }),
        "e1 should be an environment, got {}",
        items[1].as_concrete().variant_name()
    );
    assert_symbol(&items, 2, "sym_after");
    assert_symbol(&items, 3, "sym_before");
    assert!(
        matches!(items[4].as_concrete(), RObject::Environment { .. }),
        "e2 should be an environment, got {}",
        items[4].as_concrete().variant_name()
    );
    // The back reference registered after the environment: only resolves
    // correctly when the reader tracks exactly the same types as R's writer.
    assert_symbol(&items, 5, "sym_after");
    assert_string(&items, 6, "ref-aligned");

    // The two environment occurrences must be the same shared object.
    let e1 = shared_arc(&items[1]).expect("e1 should be Shared");
    let e2 = shared_arc(&items[4]).expect("e2 should be Shared");
    assert!(
        Arc::ptr_eq(&e1, &e2),
        "e1 and e2 should point to the same shared environment"
    );
}

#[test]
fn test_symbol_backreference_after_vectors() {
    if !test_data_exists() {
        eprintln!("Warning: tests/data directory not found, skipping test");
        return;
    }

    // list(x = c(10L, 20L, 30L), nm = as.name("bar"), y = c("a", "b"),
    //      nested = list(z = c(1.5, 2.5)), nm2 = as.name("bar"),
    //      tail = "after-vectors")
    let data = read_test_file("refsxp_symbol_after_vectors.rds");
    let obj = read_rds(&data).expect("Failed to parse").object;
    let items = unwrap_named_list(obj);
    assert_eq!(items.len(), 6);

    match items[0].as_concrete() {
        RObject::Integer(values) => assert_eq!(values.as_vec(), &vec![10, 20, 30]),
        other => panic!("x should be Integer, got {}", other.variant_name()),
    }
    // Vectors are never reference-tracked by R, so they must not be wrapped
    // in Shared (which would indicate they consumed a reference slot).
    assert!(
        shared_arc(&items[0]).is_none(),
        "atomic vectors must not consume reference slots"
    );

    assert_symbol(&items, 1, "bar");
    // If vectors or lists consumed reference slots, this back reference
    // would resolve past the intended entry.
    assert_symbol(&items, 4, "bar");
    assert_string(&items, 5, "after-vectors");
}

/// Visitor that counts objects and shared references while checking that the
/// traversal terminates (a misaligned reference table can produce spurious
/// cycles).
#[derive(Default)]
struct CountingVisitor {
    objects: usize,
    shared_refs: usize,
    symbols: usize,
    environments: usize,
}

impl RdsVisitor for CountingVisitor {
    type Error = std::convert::Infallible;

    fn on_object_start(
        &mut self,
        _path: &ObjectPath,
        obj_type: &str,
    ) -> Result<VisitAction, Self::Error> {
        self.objects += 1;
        match obj_type {
            "Symbol" => self.symbols += 1,
            "Environment" => self.environments += 1,
            _ => {}
        }
        Ok(VisitAction::Continue)
    }

    fn on_shared_reference(
        &mut self,
        _path: &ObjectPath,
        _target: Option<&ObjectPath>,
    ) -> Result<(), Self::Error> {
        self.shared_refs += 1;
        Ok(())
    }
}

#[test]
fn test_streaming_traversal_of_shared_env() {
    if !test_data_exists() {
        eprintln!("Warning: tests/data directory not found, skipping test");
        return;
    }

    let source = rds2rust::MmapRdsSource::from_path(Path::new("tests/data/refsxp_shared_env.rds"))
        .expect("Failed to open fixture");
    let mut visitor = CountingVisitor::default();
    traverse_rds_streaming(&source, rds2rust::ParseConfig::default(), &mut visitor)
        .expect("Streaming traversal failed");

    // s1b, e2, s2b are back references; the frame of the environment may add
    // more. What matters is that the traversal sees the shared entries and
    // the environment exactly once each.
    assert!(
        visitor.shared_refs >= 3,
        "expected at least 3 shared references, got {}",
        visitor.shared_refs
    );
    assert_eq!(
        visitor.environments, 1,
        "the environment should be visited once (back references are REFSXP)"
    );
    assert!(visitor.symbols >= 2, "symbols: {}", visitor.symbols);
}

#[test]
fn test_shared_env_roundtrip() {
    if !test_data_exists() {
        eprintln!("Warning: tests/data directory not found, skipping test");
        return;
    }

    let data = read_test_file("refsxp_shared_env.rds");
    let obj = read_rds(&data).expect("Failed to parse").object;
    let output = write_rds(&obj).expect("Failed to serialize");

    // Re-read with rds2rust: the same alignment invariants must hold.
    let reread = read_rds(&output).expect("Failed to re-read roundtripped data");
    let items = unwrap_named_list(reread.object);
    assert_eq!(items.len(), 7);
    assert_symbol(&items, 0, "sym_before");
    assert_symbol(&items, 2, "sym_after");
    assert_symbol(&items, 3, "sym_before");
    assert_symbol(&items, 5, "sym_after");
    assert_string(&items, 6, "ref-aligned");

    // Verify with R itself: symbols and environments must survive the
    // roundtrip, and both environment occurrences must stay identical.
    if !r_available() {
        eprintln!("Warning: R not available, skipping R verification");
        return;
    }
    let output_path = std::env::temp_dir().join("rds2rust_refsxp_alignment_roundtrip.rds");
    fs::write(&output_path, &output).expect("Failed to write roundtripped file");
    let r_code = format!(
        "x <- readRDS('{}'); \
         stopifnot(identical(x$s1, as.name('sym_before'))); \
         stopifnot(identical(x$s2, as.name('sym_after'))); \
         stopifnot(identical(x$s1b, as.name('sym_before'))); \
         stopifnot(identical(x$s2b, as.name('sym_after'))); \
         stopifnot(is.environment(x$e1)); \
         stopifnot(identical(x$e1, x$e2)); \
         stopifnot(identical(x$tail, 'ref-aligned')); \
         cat('PASS')",
        output_path.display()
    );
    match run_r_code(&r_code) {
        Ok(stdout) => assert!(
            stdout.contains("PASS"),
            "R verification did not pass: {}",
            stdout
        ),
        Err(err) => panic!("R failed to read roundtripped file: {}", err),
    }
    let _ = fs::remove_file(&output_path);
}

/// Regression test for the writer double-allocating reference indices for
/// plain (non-Shared) symbols.
///
/// Before the fix, `write_object`'s generic dispatch reserved an object index
/// for every plain `RObject::Symbol` via `ref_key`/`register_object_ptr`
/// (keyed by the value's transient address, which never recurs across
/// occurrences), and then `write_symbol_with_tracking`/`register_symbol_atomic`
/// allocated a *second* index for the very same emitted SYMSXP (or, for a
/// repeat occurrence, burned an index that was never consumed by any REFSXP).
/// Every later tracked object's index ends up shifted by one for each such
/// plain symbol, so any conforming reader (including R) resolves later
/// REFSXP back references to the wrong object.
///
/// This is built directly in Rust (not parsed from a fixture) because parsed
/// symbols are always `Shared`, which already took the (correct) pointer-based
/// path and did not exhibit the bug.
#[test]
fn test_plain_symbol_no_double_registration() {
    // Equivalent to R's: list(as.name("a"), as.name("b"), as.name("a"), "tail")
    let obj = RObject::List(vec![
        RObject::Symbol(Arc::from("a")),
        RObject::Symbol(Arc::from("b")),
        RObject::Symbol(Arc::from("a")),
        RObject::Character(vec![Some(Arc::from("tail"))].into()),
    ]);

    let output = write_rds(&obj).expect("Failed to serialize");

    // Re-read with rds2rust: the alignment invariants must hold.
    let reread = read_rds(&output).expect("Failed to re-read written data");
    let items = match reread.object {
        RObject::List(items) => items,
        other => panic!("Expected List, got {}", other.variant_name()),
    };
    assert_eq!(items.len(), 4);
    assert_symbol(&items, 0, "a");
    assert_symbol(&items, 1, "b");
    assert_symbol(&items, 2, "a");
    assert_string(&items, 3, "tail");

    // Verify with R itself: if the writer had burned spurious reference
    // indices, later entries (here, `tail`) would resolve to the wrong
    // object once decoded by a conforming reader.
    if !r_available() {
        eprintln!("Warning: R not available, skipping R verification");
        return;
    }
    let output_path =
        std::env::temp_dir().join("rds2rust_refsxp_alignment_plain_symbol_roundtrip.rds");
    fs::write(&output_path, &output).expect("Failed to write roundtripped file");
    let r_code = format!(
        "x <- readRDS('{}'); \
         stopifnot(identical(x, list(as.name('a'), as.name('b'), as.name('a'), 'tail'))); \
         cat('PASS')",
        output_path.display()
    );
    match run_r_code(&r_code) {
        Ok(stdout) => assert!(
            stdout.contains("PASS"),
            "R verification did not pass: {}",
            stdout
        ),
        Err(err) => panic!("R failed to read roundtripped file: {}", err),
    }
    let _ = fs::remove_file(&output_path);
}

/// Regression test covering a TAG-position plain symbol alongside a
/// non-TAG-position plain symbol of the same name, in an environment frame.
///
/// TAG symbols are written directly via `write_symbol_with_tracking` and
/// never went through the buggy `ref_key` path, but the frame's non-TAG value
/// (`b = as.name("a")`) does go through the generic dispatch. This checks
/// that the value-based dedup between the TAG occurrence of `a` and the later
/// plain-Symbol value `a` still resolves to a single REFSXP-backed index, and
/// that indices are not shifted for the objects written afterwards.
#[test]
fn test_plain_symbol_tag_and_value_dedup() {
    // Equivalent to an environment frame built from: a <- 1; b <- as.name("a")
    let env = RObject::Environment {
        enclosing: Box::new(RObject::EmptyEnv),
        frame: Box::new(RObject::Pairlist(vec![
            PairlistElement {
                tag: Some(Arc::from("a")),
                value: RObject::Real(vec![1.0].into()),
                tag_object: None,
            },
            PairlistElement {
                tag: Some(Arc::from("b")),
                value: RObject::Symbol(Arc::from("a")),
                tag_object: None,
            },
        ])),
        hashtab: Box::new(RObject::Null),
    };
    let obj = RObject::List(vec![
        env,
        RObject::Character(vec![Some(Arc::from("tail"))].into()),
    ]);

    let output = write_rds(&obj).expect("Failed to serialize");

    // Re-read with rds2rust: the alignment invariants must hold.
    let reread = read_rds(&output).expect("Failed to re-read written data");
    let items = match reread.object {
        RObject::List(items) => items,
        other => panic!("Expected List, got {}", other.variant_name()),
    };
    assert_eq!(items.len(), 2);
    assert!(
        matches!(items[0].as_concrete(), RObject::Environment { .. }),
        "expected an environment, got {}",
        items[0].as_concrete().variant_name()
    );
    assert_string(&items, 1, "tail");

    if !r_available() {
        eprintln!("Warning: R not available, skipping R verification");
        return;
    }
    let output_path =
        std::env::temp_dir().join("rds2rust_refsxp_alignment_tag_value_dedup_roundtrip.rds");
    fs::write(&output_path, &output).expect("Failed to write roundtripped file");
    let r_code = format!(
        "x <- readRDS('{}'); \
         env <- x[[1]]; \
         stopifnot(is.environment(env)); \
         stopifnot(identical(env$a, 1)); \
         stopifnot(identical(env$b, as.name('a'))); \
         stopifnot(identical(x[[2]], 'tail')); \
         cat('PASS')",
        output_path.display()
    );
    match run_r_code(&r_code) {
        Ok(stdout) => assert!(
            stdout.contains("PASS"),
            "R verification did not pass: {}",
            stdout
        ),
        Err(err) => panic!("R failed to read roundtripped file: {}", err),
    }
    let _ = fs::remove_file(&output_path);
}
