use rds2rust::*;
use std::sync::Arc;

/// Test for regression: Multiple S4 objects with identical class/package
/// were getting corrupted due to stack address reuse in write_s4_object().
///
/// The bug caused WithAttributes objects created on the stack to have the
/// same pointer address across function calls, leading to incorrect deduplication.
#[test]
fn test_multiple_s4_same_class_roundtrip() {
    // Load test data generated by tests/generate_test_data.R
    // Run `Rscript tests/generate_test_data.R` to generate test files
    let data = std::fs::read("tests/data/s4_multiple_same_class.rds")
        .expect("test file (run: Rscript tests/generate_test_data.R)");
    let obj = read_rds(&data).expect("parse original").object;

    // Write and read back
    let bytes = write_rds(&obj).expect("write");
    let obj2 = read_rds(&bytes).expect("parse roundtrip").object;

    // Verify structure: should be a list with 3 S4 objects
    if let RObject::List(items) = obj2 {
        assert_eq!(items.len(), 3, "Should have 3 items");

        // Check each S4 object has correct class and slots
        for (i, expected_name) in ["first", "second", "third"].iter().enumerate() {
            if let RObject::S4Object(s4) = &items[i] {
                assert_eq!(
                    s4.class,
                    vec![Arc::from("Container")],
                    "Item {} class mismatch",
                    i
                );

                assert_eq!(s4.slots.len(), 2, "Item {} should have 2 slots", i);

                // Verify name slot
                if let Some(RObject::Character(vec)) = s4.slots.get(&Arc::from("name")) {
                    assert_eq!(
                        vec[0].as_deref(),
                        Some(*expected_name),
                        "Item {} name mismatch",
                        i
                    );
                } else {
                    panic!("Item {} name slot missing or wrong type", i);
                }

                // Verify data slot has correct values
                if let Some(RObject::Integer(vec)) = s4.slots.get(&Arc::from("data")) {
                    let expected_base = (i as i32 + 1) * 100;
                    assert_eq!(
                        vec,
                        &vec![expected_base, expected_base + 1, expected_base + 2],
                        "Item {} data mismatch",
                        i
                    );
                } else {
                    panic!("Item {} data slot missing or wrong type", i);
                }
            } else {
                panic!(
                    "Item {} expected S4Object, got {:?}",
                    i,
                    items[i].variant_name()
                );
            }
        }
    } else {
        panic!("Expected List, got {:?}", obj2.variant_name());
    }
}

/// Test for regression: Complex S4 objects with matrices and nested S4 objects.
/// This reproduces the scenario where slot values (e.g., primary_matrix) would get
/// swapped with other slot values (e.g., secondary_matrix rownames) due to
/// WithAttributes stack address collisions.
#[test]
fn test_multiple_s4_with_matrices_roundtrip() {
    // Load test data generated by tests/generate_test_data.R
    // Run `Rscript tests/generate_test_data.R` to generate test files
    let data = std::fs::read("tests/data/s4_multiple_with_matrices.rds")
        .expect("test file (run: Rscript tests/generate_test_data.R)");
    let obj = read_rds(&data).expect("parse original").object;

    // Write and read back
    let bytes = write_rds(&obj).expect("write");
    let obj2 = read_rds(&bytes).expect("parse roundtrip").object;

    // Verify structure
    if let RObject::List(items) = obj2 {
        assert_eq!(items.len(), 3, "Should have 3 items");

        for (i, expected_label) in ["alpha", "beta", "gamma"].iter().enumerate() {
            if let RObject::S4Object(s4) = &items[i] {
                assert_eq!(
                    s4.class,
                    vec![Arc::from("MatrixContainer")],
                    "Item {} class mismatch",
                    i
                );

                // Check label slot
                if let Some(RObject::Character(vec)) = s4.slots.get(&Arc::from("label")) {
                    assert_eq!(
                        vec[0].as_deref(),
                        Some(*expected_label),
                        "Item {} label mismatch",
                        i
                    );
                } else {
                    panic!("Item {} label slot missing", i);
                }

                // Check primary_matrix is a matrix (WithAttributes with dim), not something else
                if let Some(primary) = s4.slots.get(&Arc::from("primary_matrix")) {
                    match primary {
                        RObject::WithAttributes { object, attributes } => {
                            // Should be Real vector
                            if let RObject::Real(data) = object.as_ref() {
                                assert_eq!(
                                    data.len(),
                                    4,
                                    "Item {} primary_matrix should have 4 values",
                                    i
                                );
                            } else {
                                panic!(
                                    "Item {} primary_matrix inner is {:?}, expected Real",
                                    i,
                                    object.variant_name()
                                );
                            }

                            // Check it has dimnames with correct row labels
                            if let Some(RObject::List(dimnames)) = attributes.get("dimnames") {
                                if let Some(RObject::Character(rownames)) = dimnames.first() {
                                    assert!(
                                        rownames[0].as_deref().unwrap().starts_with("Row"),
                                        "Item {} primary_matrix rownames should be Row1, Row2",
                                        i
                                    );
                                }
                            }
                        }
                        _ => {
                            panic!(
                                "Item {} primary_matrix is {:?}, expected WithAttributes",
                                i,
                                primary.variant_name()
                            );
                        }
                    }
                } else {
                    panic!("Item {} primary_matrix slot missing", i);
                }

                // Check secondary_matrix has different row labels (ItemA, ItemB)
                if let Some(secondary) = s4.slots.get(&Arc::from("secondary_matrix")) {
                    if let RObject::WithAttributes { attributes, .. } = secondary {
                        if let Some(RObject::List(dimnames)) = attributes.get("dimnames") {
                            if let Some(RObject::Character(rownames)) = dimnames.first() {
                                assert!(
                                    rownames[0].as_deref().unwrap().starts_with("Item"),
                                    "Item {} secondary_matrix rownames should be ItemA, ItemB",
                                    i
                                );
                            }
                        }
                    }
                } else {
                    panic!("Item {} secondary_matrix slot missing", i);
                }

                // Check nested S4 object
                if let Some(RObject::S4Object(nested)) = s4.slots.get(&Arc::from("nested")) {
                    assert_eq!(
                        nested.class,
                        vec![Arc::from("NestedData")],
                        "Item {} nested class mismatch",
                        i
                    );

                    if let Some(RObject::Real(values)) = nested.slots.get(&Arc::from("values")) {
                        assert_eq!(values.len(), 2, "Item {} nested should have 2 values", i);
                    } else {
                        panic!("Item {} nested values slot missing or wrong type", i);
                    }
                } else {
                    panic!("Item {} nested slot missing or wrong type", i);
                }
            } else {
                panic!(
                    "Item {} expected S4Object, got {:?}",
                    i,
                    items[i].variant_name()
                );
            }
        }
    } else {
        panic!("Expected List, got {:?}", obj2.variant_name());
    }
}
